-- FUNCIONES 

/*
	ACLARACION DE SUMA IMPORTANCIA
    JAMAS SE DEBE GUARDAR UNA CONTRASENA DE CIFRADO EN UNA BD, NI DENTRO NI FUERA DE UNA FUNCION
    PUES ABRE PROBLEMAS DE SEGURIDAD Y PODRIA SER REVELADA CON FACILIDAD, SIN EMBARGO, MIENTRAS
    CREAMOS UN DEBIDO BACKEND LAS FUNCIONES CONTENDRAN LA CONTRASENA PARA REALIZAR PRUEBAS.
*/

# FUNCION DE CIFRADO

DELIMITER $$

CREATE FUNCTION cifrado(passwd VARCHAR(255))
RETURNS VARBINARY(255)
DETERMINISTIC
BEGIN
	SET @passGen = 'My Fr0gDog #41!';
	RETURN AES_ENCRYPT(passwd, @passGen);
END$$
DELIMITER ;

# FUNCION DE DESCRIFRADO

DELIMITER $$

CREATE FUNCTION descifrado(passwd VARBINARY(255))
RETURNS VARCHAR(255)
DETERMINISTIC
BEGIN
	SET @passGen = 'My Fr0gDog #41!';
	RETURN AES_DECRYPT(passwd, @passGen);
END$$
DELIMITER ;

# FUNCION DE CALCULO DEL IVA

DELIMITER $$

CREATE FUNCTION impuesto(valor DECIMAL(10,2))
RETURNS DECIMAL (10,2)
DETERMINISTIC
BEGIN
	RETURN ROUND(valor * 0.19,2);
END$$
DELIMITER ;